INSERT INTO Account (account_id, First_Name, Last_Name, Acc_Number) VALUES (1, 'Sam', 'Kirk', 123456)
INSERT INTO Account (account_id, First_Name, Last_Name, Acc_Number) VALUES (2, 'Joe', 'Bloggs', 234567)
INSERT INTO Account (account_id, First_Name, Last_Name, Acc_Number) VALUES (3, 'Another', 'Guy', 345678)
INSERT INTO Transaction (transaction_id, transactionname, account_id) VALUES (1, 'Sam transaction1', 1)
INSERT INTO Transaction (transaction_id, transactionname, account_id) VALUES (2, 'Sam transaction1', 1)
INSERT INTO Transaction (transaction_id, transactionname, account_id) VALUES (3, 'Joe transaction1', 2)